# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: daeunki2 <daeunki2@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/15 09:40:09 by daeunki2          #+#    #+#              #
#    Updated: 2025/08/23 21:05:18 by daeunki2         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

BLACK = \033[0;30m
RED = \033[0;31m
GREEN = \033[0;32m
YELLOW = \033[0;33m
BLUE = \033[0;34m
MAGENTA = \033[0;35m
CYAN = \033[0;36m
WHITE = \033[0;37m

# Bold text colors
BOLD_BLACK = \033[1;30m
BOLD_RED = \033[1;31m
BOLD_GREEN = \033[1;32m
BOLD_YELLOW = \033[1;33m
BOLD_BLUE = \033[1;34m
BOLD_MAGENTA = \033[1;35m
BOLD_CYAN = \033[1;36m
BOLD_WHITE = \033[1;37m

# Reset color
RESET = \033[0m


NAME    = Zombie
CC      = c++
CFLAGS  = -Wall -Wextra -Werror -std=c++98

OBJ_DIR = obj
SRCS    = main.cpp Zombie.cpp
OBJS    = $(SRCS:%.cpp=$(OBJ_DIR)/%.o)

# 기본 규칙
all: $(NAME)

# 실행파일 만들기
$(NAME): $(OBJS)
	@$(CC) $(CFLAGS) $(OBJS) -o $(NAME)
	@echo "✅ Build complete: $(NAME)"

# 오브젝트 파일 만들기
$(OBJ_DIR)/%.o: %.cpp | $(OBJ_DIR)
	@$(CC) $(CFLAGS) -c $< -o $@

# obj 디렉토리 자동 생성
$(OBJ_DIR):
	@mkdir -p $(OBJ_DIR)

# 청소
clean:
	@rm -rf $(OBJ_DIR)
	@echo "🧹 Objects removed"

fclean: clean
	@rm -f $(NAME)
	@echo "🧹 Executable removed"

re: fclean all

.PHONY: all clean fclean re

